services:
  - type: web
    name: ssm-health-analytics-portal
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn deploy_secure_map:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: FLASK_ENV
        value: production
      - key: MAP_USERNAME
        value: ssm_team
      - key: MAP_PASSWORD
        value: your_secure_password_here
      - key: FLASK_SECRET_KEY
        generateValue: true
    healthCheckPath: /health 